version: '3.8'

services:
  hashwrap:
    build: 
      context: ./webapp
      dockerfile: Dockerfile
    container_name: hashwrap
    ports:
      - "5000:5000"
    volumes:
      # Mount data directories for persistence
      - ./data/uploads:/app/data/uploads
      - ./data/results:/app/data/results
      - ./wordlists:/app/wordlists
      # Mount existing hashwrap modules if available
      - ./core:/app/core:ro
      - ./utils:/app/utils:ro
    environment:
      - HASHWRAP_GPU_MODE=disabled
      - HASHWRAP_CPU_ONLY=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/login"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  hashwrap_data:
    driver: local

networks:
  default:
    name: hashwrap-network